version: '2'
services:
  php:
    build: App/.
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DOCUMENT_ROOT=/var/www/html/public
  mysql:
    build: BD/.
    tty: true 
    ports:
      - "3306:3306"
    restart: unless-stopped 
    volumes:
      - ./mysql:/var/lib/mysql